sudo: required

language: go

go:
 - 1.7

services:
 -  docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    export REPO=MarcosSegovia/MyWins
    docker build -t marcossegovia/mywins .
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push REPO:0.$TRAVIS_BUILD_NUMBER;
    fi
